### ISSUE TITLE
Route brightness not smoothly interpolated in the latest Nightly Build

### ISSUE THREAD

**Issue by Kenny-Hui** [leezer3/OpenBVE#665]
### Description

Route brightness change is not smoothly interpolated in the latest Nightly Build.
The train just seems to suddenly go dark, then suddenly go bright without any transitions.

Unfortunately I don't have any lightweight sample route for reproduction,
Please use the sample route from #492 as specified in the comment

### Related information 
* Operating system: Windows 10 21H1
* Method of control: Keyboard

**Comment by ginga81** [comment]
https://github.com/leezer3/OpenBVE/issues/492
please change from this sample route.
It is all data included and simple.

**Comment by leezer3** [comment]
Please try the latest build.

Caused by a rather irritating oddity I'd accidentally overlooked; Cab brightness is calculated from the front axle, but car brightness from the rear axle. With overbridge brightnesses, the interpolation window was short enough to be ignored....

I've fixed this issue, but have also added an additional parameter which allows us to calculate the brightness at any arbritrary point in the car. This means that on trains with bogie objects, the front and rear bogie brightnesses are independat.

**Comment by Kenny-Hui** [comment]
![image](https://user-images.githubusercontent.com/28094366/124817825-dc5e6c80-df9c-11eb-899e-e7229bcb87e1.png)
Now I am getting this error when selecting any route

**Comment by leezer3** [comment]
Can't reproduce from a fresh download of today's build, both Windows and the Debian VM.

Rather suggests to me you've extracted in an old folder and got some of the files mixed together

**Comment by Kenny-Hui** [comment]
Hmm not sure, I redownloaded it from https://vps.bvecornwall.co.uk/OpenBVE/Builds/ and still the same issue
(OpenBVE-2021-07-07.zip | 12:40:30)
Nothing got replaced, just a fresh copy of OpenBVE Nightly Build extracted using 7zip

**Comment by Kenny-Hui** [comment]
Oh it doesn't seems to like my Windows Insider Preview (Basically Win11)

Everything works properly on Win10 (Including the brightness interpolation)

Will check if it's a one-time thing (Where a restart would solve it), or it just isn't compatible with Win11 (Or my specific install)
